apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: java-apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: House of Java Applications

  # Allow manifests to deploy from any Git repos TODO change ??
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: default
    server: {{ .Values.destination.server }}
  - namespace: demo-apps
    server: {{ .Values.destination.server }}

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment,StatefulSet,Job,SA,Secret,ConfigMap etc.,
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'apps'
    kind: StatefulSet
  - group: 'batch'
    kind: Job
  - group: ""
    kind: Service
  - group: ""
    kind: ConfigMap
  - group: ""
    kind: Secret
  - group: rbac.authorization.k8s.io
    kind: "*"
  - group: ""
    kind: PersistentVolumeClaim
  - group: ""
    kind: ServiceAccount

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
