#!/usr/bin/env bash

set -euxo pipefail

# Deploy Gitea
helm repo add gitea-charts https://dl.gitea.io/charts/
helm repo update

helm upgrade \
  --install gitea gitea-charts/gitea \
  --values "$DAG_HOME/helm_vars/gitea/values.yaml" \
  --wait

# Create the default user user-01 and configure the user with default git repos
kubectl apply -k "$GITEA_CONFIG_MANIFESTS_PATH"
kubectl wait --for=condition=complete --timeout=60s -n drone job/workshop-setup
